import Head from "next/head";

import { AiFillLinkedin } from "react-icons/ai";
import { FaGithubAlt } from "react-icons/fa";
import { BsFillMoonStarsFill } from "react-icons/bs";

import { useState } from "react";

import avatar from "../public/AvatarGit.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/swapi.png";
import web2 from "../public/eSport.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Guilherme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Guilherme</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1ItrhB_0X0CmKwD4N4JLcc_aHylBGs6-V/view?usp=share_link"
                  target="_blank"
                >
                  Download CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Guilherme S Passos
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Web Front-End.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Profissional apaixonado por design e usabilidade, com habilidade
              para transformar projetos em realidade, utilizando React, Git,
              JavaScript e outras tecnologias da web.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://github.com/guilherme-369"
                className="cursor-pointer text-teal-600"
              >
                <FaGithubAlt />
              </a>
              <a
                href="https://www.linkedin.com/in/guilherme-passos369/"
                className="cursor-pointer text-teal-600"
              >
                <AiFillLinkedin />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b flex items-center justify-center  from-teal-500  rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <div className="text-center">
                <Image
                  src={avatar}
                  layout="fill"
                  objectFit="cover"
                  className="mx-auto"
                />
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Sobre Mim</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Olá, meu nome é Guilherme e sou um programador junior
              recém-formado. Desde que comecei a aprender programação, fiquei
              fascinado com a habilidade de criar soluções complexas com código.
              Além de minha formação na Kenzie Academy, tenho experiência em
              HTML | CSS | JAVASCRIPT | REACT | TYPESCRIPT | GITHUB | GITFLOW |
              SCRUM | TAILWIND CSS | NEXT JS
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Estou ansioso por colocar meus conhecimentos em prática e aprender
              ainda mais na minha jornada como programador. Estou procurando uma
              equipe colaborativa e inovadora para ajudar a desenvolver minhas
              habilidades e crescer profissionalmente.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Criação de Sites
              </h3>
              <p className="py-2">Criando sites responsivos e elegantes</p>
              <h4 className="py-4 text-teal-600">Ferramentas que eu uso</h4>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Vite</p>
              <p className="text-gray-800 py-1">Next.JS</p>
              <p className="text-gray-800 py-1">TypeScript</p>
              <p className="text-gray-800 py-1">Styled-Components</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Controle de Código
              </h3>
              <p className="py-2">Minhas ferramentas para controle do código</p>
              <h4 className="py-4 text-teal-600">Ferramentas que eu uso</h4>
              <p className="text-gray-800 py-1">Git</p>
              <p className="text-gray-800 py-1">GitHub</p>
              <p className="text-gray-800 py-1">GitFlow</p>
              <p className="text-gray-800 py-1">conventional commits</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Organização</h3>
              <p className="py-2">
                gerenciamento do meu dia a dia e dos meus projetos
              </p>
              <h4 className="py-4 text-teal-600">Ferramentas que eu uso</h4>
              <p className="text-gray-800 py-1">Notion</p>
              <p className="text-gray-800 py-1">Google Agenda</p>
              <p className="text-gray-800 py-1">Trello</p>
              <p className="text-gray-800 py-1">SCRUM</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfolio</h3>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Alguns dos meus projetos que me ajudaram a aprender a programar
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href="https://swapi-kappa.vercel.app/" target="_blank">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="#" target="_blank">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                />
              </a>
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
